### ISSUE TITLE
Make smbus optional

### ISSUE THREAD

**Issue by stefaang** [michaelroland/wdnas-dl2100-hwtools#5]
The smbus python package is only required for the memory sensor.
It's not always that easy to install this on other systems e.g. on FreeBSD it's not available for python3.

It would be nice if this hard requirement could be bypassed / softened.
- e.g. when no memory dimms are monitored, smbus is not necessary
- smbus2 is a pure python alternative for smbus, available through pip

**Comment by michaelroland** [comment]
Implemented.
